### ISSUE TITLE
AbsoluteDate's constructor improvements

### ISSUE THREAD

**Issue by adaniloff** [assoconnect/php-date#5]
2 suggestions:
- the constructor will not handle well timestamp-like arguments because of concatenation (see my comments below)
- it could be improved by adding an optional `$timezone` (or `$timezoneFormat`) as a 3rd argument (however I don't like long argument lists so it really is up to you)

An extract of code from the constructor as it is for now, with some comments of mine : 

```php
    public function __construct(string $date, string $format = null)
    {
        if (!$format) {
            $format = self::DEFAULT_DATE_FORMAT;
        }

        $timezone = new \DateTimeZone('UTC'); // could be an optional argument

        // the 2 lines below can cause some trouble
        $format .= 'H:i:s';
        $date .= '00:00:00';
    }
```

See below : 
```php
$datetime = new DateTime();

$date = new AbsoluteDate($datetime->format('Y-m-d H:i:s')); // won't work, but this seems normal
$date = new AbsoluteDate($datetime->format('U'), 'U'); // won't work either, but this DOES NOT seems normal at all !

$date = new AbsoluteDate($datetime->format('Y-m-d H:i:s'), 'Y-m-d H:i:s'); // this, however, works fine
```

**Comment by sylfabre** [comment]
@adaniloff thank you for this feedback

The general intent of this lib is:
- use the constructor if you have a date-like format (like Y/m/d, Y-m-d, ...) but don't use it with hour parts (like H:i:s, U, ...)
- use the static method `createInTimezone()` with a DateTime

I was thinking of allowing just some formats or (parts of format) like "Y", "m", "d", ... but it seems over-engineering.

I'll update the PHPDoc of the constructor to make it more understandable.

I've noticed the readme has some issue explaining how it works, I'll fix them.

**Comment by adaniloff** [comment]
> I was thinking of allowing just some formats or (parts of format) like "Y", "m", "d", ... but it seems over-engineering.

Those parts of formats already work ! For example: `new AbsoluteDate('2020', 'Y')` is already working fine.

It's mainly with timestamps :)

**Comment by sylfabre** [comment]
@adaniloff You should use the static method `createInTimezone()` if you're working with arguments requiring a timezone.
